import { Roboto, Poppins, Orbitron } from "next/font/google";
import "@/styles/globals.css";
import Container from "@/utils/container";
import Header from "@/components/header/header";
import { ApiProvider } from "@/context/api-context";
import Footer from "@/components/footer/footer";

// import "@/styles/reset.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});
const orbitton = Orbitron({
  variable: "--font-orbitton",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Pide Vakti",
  description: "Generated by Emirhan Çöpoğlu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body
        className={`${roboto.variable}  ${poppins.variable} ${orbitton.variable} antialiased`}
      >
        <ApiProvider>
          <Container>
            <Header />
            {children}
            <Footer />
          </Container>
        </ApiProvider>
      </body>
    </html>
  );
}
