import { Roboto, Poppins, Orbitron } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { Toaster } from "@/components/ui/sonner";
import { ApiProvider } from "@/context/api-context";
import "@/styles/globals.css";
import Container from "@/utils/container";
import Head from "next/head";
// import "@/styles/reset.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});
const orbitton = Orbitron({
  variable: "--font-orbitton",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Pide Vakti",
  description: "Generated by Emirhan Çöpoğlu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr" suppressHydrationWarning>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body
        className={`${roboto.variable}  ${poppins.variable} ${orbitton.variable} antialiased`}
      >
        <ApiProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Container>
              <Header />

              {children}
              <Toaster richColors position="top-center" closeButton />

              <Footer />
              <Head>
                <meta
                  name="viewport"
                  content="width=device-width, initial-scale=1"
                />
              </Head>
            </Container>
          </ThemeProvider>
        </ApiProvider>
      </body>
    </html>
  );
}
